Grzadka/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Grzadka.Models
{
    public class Category
    {
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string IconFileName { get; set; }
        public ICollection<Plant> Plants { get; set; }
    }
}

Grzadka/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Grzadka.Models
{
    public class Order
    {
        public int OrderId { get; set; } //klucz glowny 

        public string UserId { get; set; }
        //public virtual ApplicationUser User { get; set; }

        [Required(ErrorMessage = "Musisz wprowadzić imię")]
        [StringLength(100)]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Musisz wprowadzć nazwisko")]
        [StringLength(150)]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Nie wprowadzono adresu")]
        [StringLength(150)]
        public string Address { get; set; }

        [Required(ErrorMessage = "Wprowadź kod pocztowy i miasto")]
        [StringLength(50)]
        public string CodeAndCity { get; set; }

        [Required(ErrorMessage = "Musisz wprowadzić numer telefonu")]
        [StringLength(20)]
        [RegularExpression(@"(\+\d{2})*[\d\s-]+",
            ErrorMessage = "Błędny format numeru telefonu.")]
        public string PhoneNumber { get; set; }

        [Required(ErrorMessage = "Wprowadź swój adres e-mail.")]
        [EmailAddress(ErrorMessage = "Błędny format adresu e-mail.")]        
        public string Email { get; set; }

        public string Comment { get; set; }
        public DateTime DateCreated { get; set; }
        public OrderState OrderState { get; set; }

        public decimal TotalPrice { get; set; }

        public List<OrderItem> OrderItems { get; set; }
    }

    public enum OrderState
    {
        [Display(Name="nowe")]
        New,

        [Display(Name="wysłane")]
        Shipped
    }
 }

Grzadka/Models/OrderItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Grzadka.Models
{
    public class OrderItem
    {
        public int OrderItemId { get; set; }
        public int OrderId { get; set; }
        public int PlantId { get; set; } //klucz obcy
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }

        public virtual Plant Plant { get; set; }
        public virtual Order Order { get; set; }
    }
}

Grzadka/Models/Plant.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Grzadka.Models
{
    public class Plant
    {
        public int PlantId{ get; set; }
        public int CategoryId { get; set; }
        public string PlantName { get; set; }

        public int StandPoint { get; set; }
        public int Humidity { get; set; }
        public int Size { get; set; }
        public int Decoration { get; set; }
        public int Growth { get; set; }
        public int Spitz { get; set; } //zraszanie
        public int Rambling { get; set; } //pnąca
        public int Difficulty { get; set; } //uprawa

        public DateTime DateAdded { get; set; }
        public string CoverFileName { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public bool IsBestseller { get; set; }
        public bool IsHidden { get; set; }

        public virtual Category Category{ get; set; }

    }
}

Grzadka/ViewModels/HomeViewModel.cs
using Grzadka.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Grzadka.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Plant> Bestsellers { get; set; }
        public IEnumerable<Plant> NewArrivals { get; set; } //nowododane
        public IEnumerable<Category> Categories { get; set; } 
    }
}

Grzadka/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Grzadka.DAL;
using Grzadka.Models;
using Grzadka.ViewModels;

namespace Grzadka.Controllers
{
    public class HomeController : Controller
    {
        private StoreContext db = new StoreContext();
        // GET: Home
        public ActionResult Index()
        {
            var categories = db.Categories;
            var newArrivals = db.Plants.Where(a => !a.IsHidden).OrderByDescending(a => a.DateAdded).Take(3).ToList();
            var bestsellers = db.Plants.Where(a => !a.IsHidden && a.IsBestseller).OrderBy(g => Guid.NewGuid()).Take(3).ToList(); //losuje 3 bestsellery

            var vm = new HomeViewModel()
            {
                Bestsellers = bestsellers,
                Categories = categories,
                NewArrivals = newArrivals
            };

            return View(vm);
        }
        public ActionResult StaticContent(string viewname)
        {
            return View(viewname);
        }
    }
}

Grzadka/Controllers/HomeViewController.cs
using Grzadka.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Grzadka.Controllers
{
   public class HomeViewController
    {
        
    }
}

Grzadka/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Grzadka.Controllers
{
    public class StoreController : Controller
    {
        // GET: Store
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult List(string categoryname) //zmiana!!!!!!
        {
            return View();
        }
    }
}

Grzadka/Views/Home/Index.cshtml
@model Grzadka.ViewModels.HomeViewModel


@{
    ViewBag.Title = "Witaj";
}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
    <link href="../Content/Site-prototype.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
</head>
<body>

    <nav class="genres-horizontal">
        <ul>
            @foreach (var category in Model.Categories)
            {
                <li>
                    <a href="@Url.Action("List", "Store", new { categoryname = category.Name.ToLower() })"
                        style="background-image: url(@Url.CategoryIconPath(category.IconFileName)); ">
                        @category.Name  
                    </a>
                </li>
            }
        </ul>
        <a href="">
            <img id="baner-main" src="../Content/Images/separator.png"  />
        </a>
        <a href="">
            <img id="baner-main" src="../Content/Images/baner-mainn.png" />
        </a>
    </nav>
    <section>
        <ul class="ThreeColumnsCoversList large-cover-list">
            <li>
                <article>
                    <a class="addtocartlink" href="aaaa">
                        <img src="../Content/Images/cart.png" />
                    </a>
                    <a class="productdetailslink" href="asd">
                        <div class="newFlag"></div>
                        <img class="album-cover" src="../Content/Covers/Adenium opasłe _Róża Pustyni_.jpg" />
                        <h1>
                            Testowy obrazek
                        </h1>
                    </a>
                </article>
            </li>
            <li>
                <article>
                    <a class="addtocartlink" href="aaaa">
                        <img src="../Content/Images/cart.png" />
                    </a>
                    <a class="productdetailslink" href="asd">
                        <div class="newFlag"></div>
                        <img class="album-cover" src="../Content/Covers/Aeschynanthus _Mona Lisa_.jpg" />
                        <h1>
                            Testowy obrazek
                        </h1>
                    </a>
                </article>
            </li>
            <li>
                <article>
                    <a class="addtocartlink" href="aaaa">
                        <img src="../Content/Images/cart.png" />
                    </a>
                    <a class="productdetailslink" href="asd">
                        <div class="newFlag"></div>
                        <img class="album-cover" src="../Content/Covers/Alocasia _Polly_ Alokazja.jpg" />
                        <h1>
                            Testowy obrazek
                        </h1>
                    </a>
                </article>
            </li>
        </ul>
    </section>

    <section>
        <ul class="ThreeColumnsCoversList large-cover-list">
            <li>
                <article>
                    <a class="addtocartlink" href="aaaa">
                        <img src="../Content/Images/cart.png" />
                    </a>
                    <a class="productdetailslink" href="asd">
                        <div class="bestsellerFlag"></div>
                        <img class="album-cover" src="../Content/Covers/aloes.jpg" />
                        <h1>
                            Testowy obrazek
                        </h1>
                    </a>
                </article>
            </li>
            <li>
                <article>
                    <a class="addtocartlink" href="aaaa">
                        <img src="../Content/Images/cart.png" />
                    </a>
                    <a class="productdetailslink" href="asd">
                        <div class="bestsellerFlag"></div>
                        <img class="album-cover" src="../Content/Covers/bananowiec.jpg" />
                        <h1>
                            Testowy obrazek
                        </h1>
                    </a>
                </article>
            </li>
            <li>
                <article>
                    <a class="addtocartlink" href="aaaa">
                        <img src="../Content/Images/cart.png" />
                    </a>
                    <a class="productdetailslink" href="asd">
                        <div class="bestsellerFlag"></div>
                        <img class="album-cover" src="../Content/Covers/Begonia koralowa kopia.jpg" />
                        <h1>
                            Testowy obrazek
                        </h1>
                    </a>
                </article>
            </li>
        </ul>
    </section>



</body>
</html>

Grzadka/Views/Home/Kontakt.cshtml
@{
    ViewBag.Title = "Kontakt";
    Layout = "~/Views/Shared/_StoreLayout.cshtml";
}

<h2>Kontakt</h2>

<div style="margin-top: 20px; line-height: 22px;">
    Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.
    Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.
    Fusce non varius purus aenean nec magna felis fusce vestibulum velit mollis odio sollicitudin lacinia aliquam posuere, sapien elementum lobortis tincidunt, turpis dui ornare nisl, sollicitudin interdum turpis nunc eget.
    Sem nulla eu ultricies orci praesent id augue nec lorem pretium congue sit amet ac nunc fusce iaculis lorem eu diam hendrerit at mattis purus dignissim vivamus mauris tellus, fringilla.
    Vel dapibus a, blandit quis erat vivamus elementum aliquam luctus etiam fringilla pretium sem vitae sodales mauris id nulla est praesent laoreet, metus vel auctor aliquam, eros purus vulputate leo.
    Eget consequat neque quam id tellus duis ultricies tempor tortor, vitae dignissim ligula mattis nec in hac habitasse platea dictumst ut arcu enim, dictum quis ultrices id, sagittis eget nulla.
    Sed nunc mi, congue ut ultricies ac, varius a eros donec porttitor, libero fermentum fringilla laoreet, eros arcu sodales ante, ut dictum risus lectus vel quam integer ultricies, nunc eget.
    Elementum euismod, orci enim vestibulum orci, nec suscipit urna odio et tellus suspendisse suscipit orci sit amet sem venenatis nec lobortis sem suscipit nullam nec imperdiet velit mauris eu nisi.
    A felis imperdiet porta at ac nulla vivamus faucibus felis nec dolor pretium eget pellentesque dolor suscipit maecenas vitae enim arcu, at tincidunt nunc pellentesque eleifend vulputate lacus, vel semper.
    Sem ornare sit amet proin sem sapien, auctor vel faucibus id, aliquet vitae ipsum etiam auctor ultricies ante, at dapibus urna viverra sed nullam mi arcu, tempor vitae interdum a.
    Sodales non urna vestibulum dignissim auctor mauris, ac elementum purus fermentum vitae duis placerat laoreet risus, sit amet eleifend tellus lobortis non vivamus iaculis dapibus leo a ornare cras vel.
    Sem at felis convallis mollis posuere ultrices dolor sed tellus arcu, accumsan a consectetur sit amet, volutpat eget lorem phasellus quis ipsum orci integer sodales tincidunt nibh a elementum ut.
    Ac libero nec orci euismod euismod nec at nulla duis malesuada faucibus porta aliquam nec consequat eros sed porttitor placerat dolor, accumsan imperdiet neque ornare in aenean non elit non.
    Leo porta mattis mauris non dolor nunc, id congue odio donec tellus nisl, semper id consectetur vitae, dapibus dictum nisl morbi sed augue purus sed dictum diam convallis tortor interdum.
    Volutpat phasellus dapibus arcu sit amet neque vulputate sed elementum orci fringilla in hac habitasse platea dictumst maecenas ut dui diam curabitur adipiscing vestibulum libero, nec varius dui pulvinar eget.
    Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; aliquam dui neque, varius eu laoreet vel.
</div>

Grzadka/Views/Home/Onas.cshtml
@{
    ViewBag.Title = "Onas";
    Layout = "~/Views/Shared/_StoreLayout.cshtml";
}

<h2>Onas</h2>

<div style="margin-top: 20px; line-height: 22px;">
    Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.
    Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante.
    Fusce non varius purus aenean nec magna felis fusce vestibulum velit mollis odio sollicitudin lacinia aliquam posuere, sapien elementum lobortis tincidunt, turpis dui ornare nisl, sollicitudin interdum turpis nunc eget.
    Sem nulla eu ultricies orci praesent id augue nec lorem pretium congue sit amet ac nunc fusce iaculis lorem eu diam hendrerit at mattis purus dignissim vivamus mauris tellus, fringilla.
    Vel dapibus a, blandit quis erat vivamus elementum aliquam luctus etiam fringilla pretium sem vitae sodales mauris id nulla est praesent laoreet, metus vel auctor aliquam, eros purus vulputate leo.
    Eget consequat neque quam id tellus duis ultricies tempor tortor, vitae dignissim ligula mattis nec in hac habitasse platea dictumst ut arcu enim, dictum quis ultrices id, sagittis eget nulla.
    Sed nunc mi, congue ut ultricies ac, varius a eros donec porttitor, libero fermentum fringilla laoreet, eros arcu sodales ante, ut dictum risus lectus vel quam integer ultricies, nunc eget.
    Elementum euismod, orci enim vestibulum orci, nec suscipit urna odio et tellus suspendisse suscipit orci sit amet sem venenatis nec lobortis sem suscipit nullam nec imperdiet velit mauris eu nisi.
    A felis imperdiet porta at ac nulla vivamus faucibus felis nec dolor pretium eget pellentesque dolor suscipit maecenas vitae enim arcu, at tincidunt nunc pellentesque eleifend vulputate lacus, vel semper.
    Sem ornare sit amet proin sem sapien, auctor vel faucibus id, aliquet vitae ipsum etiam auctor ultricies ante, at dapibus urna viverra sed nullam mi arcu, tempor vitae interdum a.
    Sodales non urna vestibulum dignissim auctor mauris, ac elementum purus fermentum vitae duis placerat laoreet risus, sit amet eleifend tellus lobortis non vivamus iaculis dapibus leo a ornare cras vel.
    Sem at felis convallis mollis posuere ultrices dolor sed tellus arcu, accumsan a consectetur sit amet, volutpat eget lorem phasellus quis ipsum orci integer sodales tincidunt nibh a elementum ut.
    Ac libero nec orci euismod euismod nec at nulla duis malesuada faucibus porta aliquam nec consequat eros sed porttitor placerat dolor, accumsan imperdiet neque ornare in aenean non elit non.
    Leo porta mattis mauris non dolor nunc, id congue odio donec tellus nisl, semper id consectetur vitae, dapibus dictum nisl morbi sed augue purus sed dictum diam convallis tortor interdum.
    Volutpat phasellus dapibus arcu sit amet neque vulputate sed elementum orci fringilla in hac habitasse platea dictumst maecenas ut dui diam curabitur adipiscing vestibulum libero, nec varius dui pulvinar eget.
    Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; aliquam dui neque, varius eu laoreet vel.
</div>

Grzadka/Views/Home/Regulamin.cshtml
@{
    ViewBag.Title = "Regulamin";
    Layout = "~/Views/Shared/_StoreLayout.cshtml";
}

<h2>Regulamin</h2>

<div style="margin-top: 20px; line-height: 22px;">
    Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.dunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut laoreet ac, aliquam sit amet justo nunc tempor, metus vel.

</div>

Grzadka/Views/Home/Wysylka.cshtml
@{
    ViewBag.Title = "Wysylka";
    Layout = "~/Views/Shared/_StoreLayout.cshtml";
}

<h2>Wysylka</h2>

<div style="margin-top: 20px; line-height: 22px;">
    Sapien elit in malesuada semper mi, id sollicitudin urna fermentum.
    Ut fusce varius nisl ac ipsum gravida vel pretium tellus.
    Tincidunt integer eu augue augue nunc elit dolor, luctus placerat.
    Scelerisque euismod, iaculis eu lacus nunc mi elit, vehicula ut.
    Laoreet ac, aliquam sit amet justo nunc tempor, metus vel.
    Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio.
    Eget lorem nulla condimentum tempor mattis ut vitae feugiat augue.
    Cras ut metus a risus iaculis scelerisque eu ac ante.
    Fusce non varius purus aenean nec magna felis fusce vestibulum.
    Velit mollis odio sollicitudin lacinia aliquam posuere, sapien elementum lobortis.
    Tincidunt, turpis dui ornare nisl, sollicitudin interdum turpis nunc eget.
    Sem nulla eu ultricies orci praesent id augue nec lorem.
    Pretium congue sit amet ac nunc fusce iaculis lorem eu.
    Diam hendrerit at mattis purus dignissim vivamus mauris tellus, fringilla.
    Vel dapibus a, blandit quis erat vivamus elementum aliquam luctus.
    Etiam fringilla pretium sem vitae sodales mauris id nulla est.
    Praesent laoreet, metus vel auctor aliquam, eros purus vulputate leo.
    Eget consequat neque quam id tellus duis ultricies tempor tortor.
    Vitae dignissim ligula mattis nec in hac habitasse platea dictumst.
    Ut arcu enim, dictum quis ultrices id, sagittis eget nulla.
    Sed nunc mi, congue ut ultricies ac, varius a eros.
    Donec porttitor, libero fermentum fringilla laoreet, eros arcu sodales ante.
    Ut dictum risus lectus vel quam integer ultricies, nunc eget.
    Elementum euismod, orci enim vestibulum orci, nec suscipit urna odio.
    Et tellus suspendisse suscipit orci sit amet sem venenatis nec.
    Lobortis sem suscipit nullam nec imperdiet velit mauris eu nisi.
    A felis imperdiet porta at ac nulla vivamus faucibus felis.
    Nec dolor pretium eget pellentesque dolor suscipit maecenas vitae enim.
    Arcu, at tincidunt nunc pellentesque eleifend vulputate lacus, vel semper.
    Sem ornare sit amet proin sem sapien, auctor vel faucibus.
    Id, aliquet vitae ipsum etiam auctor ultricies ante, at dapibus.
    Urna viverra sed nullam mi arcu, tempor vitae interdum a.
    Sodales non urna vestibulum dignissim auctor mauris, ac elementum purus.
    Fermentum vitae duis placerat laoreet risus, sit amet eleifend tellus.
    Lobortis non vivamus iaculis dapibus leo a ornare cras vel.
    Sem at felis convallis mollis posuere ultrices dolor sed tellus.
    Arcu, accumsan a consectetur sit amet, volutpat eget lorem phasellus.
    Quis ipsum orci integer sodales tincidunt nibh a elementum ut.
    Ac libero nec orci euismod euismod nec at nulla duis.
    Malesuada faucibus porta aliquam nec consequat eros sed porttitor placerat.
    Dolor, accumsan imperdiet neque ornare in aenean non elit non.
    Leo porta mattis mauris non dolor nunc, id congue odio.
    Donec tellus nisl, semper id consectetur vitae, dapibus dictum nisl.
    Morbi sed augue purus sed dictum diam convallis tortor interdum.
    Volutpat phasellus dapibus arcu sit amet neque vulputate sed elementum.
    Orci fringilla in hac habitasse platea dictumst maecenas ut dui.
    Diam curabitur adipiscing vestibulum libero, nec varius dui pulvinar eget.
    Vestibulum ante ipsum primis in faucibus orci luctus et ultrices.
    Posuere cubilia curae; aliquam dui neque, varius eu laoreet vel.
</div>

Grzadka/Views/Shared/_StoreLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link href="@Url.Content("~/Content/Site-prototype.css")" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>

    <header>
        <div style="overflow: hidden;">
            <a id="facebook-header" href="">
                DOŁĄCZ DO 1500 FANÓW NA FB
            </a>

            <a id="cart-header-link" href="">
                KOSZYK (0)
                <span></span>
            </a>
        </div>
        <a id="main-header-logo" href="@Url.Content("~/")">           
            <img src="@Url.Content("~/Content/Images/logo-main.png")" class="center" />
        </a>
    </header>

    <div> 
        @RenderBody();
    </div>

    <footer>
        <nav>
            <ul>
                <li><a href="@Url.Action("StaticContent", "Home", new { viewname = "Onas" })">O nas</a></li>
                <li><a href="@Url.Action("StaticContent", "Home", new { viewname = "Kontakt" })">Kontakt</a></li>
                <li><a href="@Url.Action("StaticContent", "Home", new { viewname = "Wysylka" })">Wysyłka</a></li>
                <li><a href="@Url.Action("StaticContent", "Home", new { viewname = "Regulamin" })">Regulamin</a></li>
            </ul>
        </nav>
        <div id="footer-cd-logo">
            <img src="@Url.Content("~/content/images/footer-cd.png")" />
        </div>

        <div id="footer-copyright">
            Copyright &copy; 2013 Spod Igły
        </div>
    </footer>
    @RenderSection("ScriptsBottom",required:false)

</body>
</html>

Grzadka/Views/Store/List.cshtml
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_StoreLayout.cshtml";
}

<h2>List</h2>